### ISSUE TITLE
R21200 wrong mask diplayed

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#100]
The good tex1_256x256_$_87c215047e927565_9 : 
![tex1_256x256_$_87c215047e927565_9 (good)](https://user-images.githubusercontent.com/48800201/59472198-f1a85180-8e3d-11e9-93da-f9bc82f27186.png)

There might be other duplicates involved.

**Comment by MoArtis** [comment]
Our 100th Issue on this project! 🎈 🎉 @saeedalshaikhpygas @iFrankWesker @Kayael76 Congrats! Ahah 😃

**Comment by MoArtis** [comment]
tbt

**Comment by MoArtis** [comment]
Fixed
