### ISSUE TITLE
R21302 is indeed supposed to have mask data

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#101]
![tex1_256x256_$_456c1142aee47049_9](https://user-images.githubusercontent.com/48800201/59542075-65ad2d00-8f04-11e9-928d-8381f4f43c59.png)

Here's the GC dump : tex1_256x256_$_456c1142aee47049_9

For now the GC mask upscaled is fully transparent.

**Comment by MoArtis** [comment]
I do not have any mask data coming from the RDT file. So... is there a alternate / duplicate version of that BG?

**Comment by Kayael76** [comment]
Ah jeez, look R21412. Slippery bastard.

**Comment by MoArtis** [comment]
Ok cool! Don't hesitate to add the upscaled version in gdrive. For now I just copied the file and renamed it locally.
tbt

**Comment by MoArtis** [comment]
![GLEE08-63](https://user-images.githubusercontent.com/3904610/60383162-218f6000-9aa0-11e9-8af1-cea130a00c5b.png)

Fixed I guess 😂 Hard to tell
