### ISSUE TITLE
d3d12.dll could not be loaded.

### ISSUE THREAD

**Issue by Alex062019** [MoArtis/ResidentEvilSeamlessHdProject#103]
Can't run Resident Evil 2.iso on custom Dolphin-x64-RE2SHDP-1.0

Sony VAIO SVE1511C1RB
Pentium B970 2.3 GHz
RAM 4 GB
Win7x64 Service Pack 1
Intel HD Graphics

Every time I got these errors:
d3d12.dll could not be loaded.
Failed to create D3D12 context
Failed to initialize video backend!

Is it possible to run RE2 on that emulator with such a notebook? Please help!

**Comment by Kayael76** [comment]
You cannot run Dolphin with DirectX 12 backend on your computer, you should go under Graphics > General and choose OpenGL. Maybe lower the internal resolution to 2x instead of 4x. 
Under Graphics > Advcanced, you should uncheck Prefetch Custom Textures, you don't have enough RAM for this option. 
But even with this we cannot guarantee a flawless experience with this configuration.

**Comment by MoArtis** [comment]
I would recommend to try Dx11, Vulkan and then OpenGL in this order.
To avoid further issue of this nature, we will switch to Dx11 as the default backend.
Also, as far as I know the default configuration is already set to x2 internal resolution with the anti-aliasing set 2x SSAA.

**Comment by MoArtis** [comment]
@Alex062019 is your problem solved?

**Comment by Alex062019** [comment]
> @Alex062019 is your problem solved?

It turns out in my case I am able to run the game only with these settings:
OpenGL
Auto or Native Internal Resolution (Multiple of 640x528)
Anti-Aliasing: None

I'm still getting the error:
"Failed to create shared context for shader compiling."

But at least the game is running now. Unfortunately all I get is 3-5 fps in the actual game. So I think it's all I can have with my notebook. Well, thank you guys anyway!

**Comment by MoArtis** [comment]
👀💦 wow Is that an old or low tier laptop? It's an old game but the emulator itself is pretty demanding for sure.

Do you have an IGP (integrated graphics processor) or a dedicated GPU on your laptop? Maybe it is not being used but it's unlikely.

**Comment by Alex062019** [comment]
>  wow Is that an old or low tier laptop? It's an old game but the emulator itself is pretty demanding for sure.
> 
> Do you have an IGP (integrated graphics processor) or a dedicated GPU on your laptop? Maybe it is not being used but it's unlikely.

Yes, its Sony VAIO SVE1511C1RB with Intel HD Graphics. Pretty old laptop.
