### ISSUE TITLE
Vectorize map textures

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#105]
The upscaled map textures are available here: RE3 Seamless HD Project\GLEE08\User Interface\Maps

![image](https://user-images.githubusercontent.com/3904610/59814267-47ea2880-9347-11e9-9269-307507e2db27.png)

**Comment by Kayael76** [comment]
I couldn't tell the root of the problem but when you're in a room, the blue and red part are other dumps. So in theory, you'd have to open the map in every room of the game to dump everything correctly. My best advice would be to forget about the map upscaling entirely. 

![GLEE08-65](https://user-images.githubusercontent.com/48800201/59967057-60b03500-9525-11e9-94fa-eb1c170ddcdb.jpg)

**Comment by MoArtis** [comment]
I will investigate a bit today. The problem might be that I dumped the maps with any red or blue displayed on the map. 🤔 Do you have saves at various location like the ones provided by @saeedalshaikhpygas for RE2? I have a save but it's just one save at the very end with a ton of stuff.

**Comment by MoArtis** [comment]
Good news, the non-green parts of the map come as big chunks packed in one texture. So even if I never saw the bar in blue I already dumped it in a new play through.

![tex1_256x256_113ebba103a7717d_cedb5497b2f6e3a9_8](https://user-images.githubusercontent.com/3904610/59971313-30f84000-95ac-11e9-97da-81551b7c41ac.png)

I will go through the entire game today and carefully open the map as often as possible. Turbo pain in the butt but it is also a good excuse to play the pack entirely. 😃

**Comment by MoArtis** [comment]
I think we are pretty much done with the map. Obviously, with such process, I certainly missed a couple of dumps but I guess that would be good enough for a 1.0.
Have a look but for now I will just close that task. :)
