### ISSUE TITLE
Missing map titles

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#106]
tex1_128x64_3bec29be1ac47f23_36b98e79c4c21477_8:
![tex1_128x64_3bec29be1ac47f23_36b98e79c4c21477_8](https://user-images.githubusercontent.com/3904610/59819330-f5663780-9359-11e9-8857-09c094fdd067.png)

tex1_128x64_678e47ad31316cc6_36b98e79c4c21477_8:
![tex1_128x64_678e47ad31316cc6_36b98e79c4c21477_8](https://user-images.githubusercontent.com/3904610/59819331-f5663780-9359-11e9-9926-7d565e1e69b0.png)

**Comment by Kayael76** [comment]
Fixed versions addes in the 1.1 update pack and the full pack.

**Comment by MoArtis** [comment]
![GHAE08-2](https://user-images.githubusercontent.com/3904610/59929668-e83d6b80-9473-11e9-8b3d-3bf7e3cc8011.png)
![GHAE08-1](https://user-images.githubusercontent.com/3904610/59929670-e8d60200-9473-11e9-83cc-92cea688809b.png)

 Tested and validated! 👌
