### ISSUE TITLE
Modified Room 104_04 visuals is not matching colliders placement

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#107]
![GHAE08-5](https://user-images.githubusercontent.com/3904610/59819851-37907880-935c-11e9-85c3-408b67f0de49.png)

But since it is not easily noticeable and the room looks pretty good, I recommend to ignore the issue for now.

**Comment by Kayael76** [comment]
Yeah the perspective doesn't perfectly match the original but the overall improvement is too much a benefit. We can ignore this little flaw.
