### ISSUE TITLE
Alt Mask Issue with ROOM_601_02

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#108]
![GHAE08-12](https://user-images.githubusercontent.com/3904610/59824453-b6d57a80-9363-11e9-8d69-7f7410323b62.png)
![GHAE08-11](https://user-images.githubusercontent.com/3904610/59824454-b6d57a80-9363-11e9-830c-18ff6ac65069.png)

This project is a nightmare that keeps on delivering. :goberserk:

**Comment by Kayael76** [comment]
Jeez I wonder how this one slipped through. I guess it never shocked me but now I can't unsee it haha.

**Comment by MoArtis** [comment]
The texture is ready to be upscaled. 😃

![ROOM_601_02_altMaskSource](https://user-images.githubusercontent.com/3904610/59863937-57ee2080-93b8-11e9-9365-b7a10339e7ab.png)

ROOM_601_02_altMaskSource.png

I also put the AMS in the root folder of "RE2 Seamless HD Project" on Gdrive.

**Comment by Kayael76** [comment]
Ok it's available in RE2 Seamless HD Project\Kayael Updates\Upscaled BG and alt mask sources\Alt mask sources

**Comment by Kayael76** [comment]
I put the original with the others. Made small edits to get rid of artifacts around the screen but I couldn't do much for the screen itself.

**Comment by MoArtis** [comment]
![Uploading GHAE08-19.png…]()
