### ISSUE TITLE
Distracting melting text in ROOM_702_04

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#109]
![GHAE08-13](https://user-images.githubusercontent.com/3904610/59824687-775b5e00-9364-11e9-9a3f-a26287aa4963.png)

Low priority of course. Not even mandatory for 1.1 imho.

**Comment by Kayael76** [comment]
Nah let's not bother with small improvements for now. A great deal has already been done.

**Comment by Kayael76** [comment]
Fixed with new upscales.
