### ISSUE TITLE
Missing right part dump of ROOM_10B_10

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#110]
Chest closed is missing the right part upscaled so here's the dump : 

tex1_128x160_de180780b0f12d0f_5

![tex1_128x160_de180780b0f12d0f_5](https://user-images.githubusercontent.com/48800201/59877947-6da71a00-93a7-11e9-8bbe-1b7bb014759d.png)

Chest open is another BG and is fine. I also put it at the root of RE2 SHDP.

**Comment by MoArtis** [comment]
For now, that room is matched to tex1_128x160_3d04c5281ad7f536_5

I will investigate a bit to fix the data. Certainly a mismatch.

**Comment by MoArtis** [comment]
Ok It was really a missing dump, I added it ROOM_10B_11 (there was no right part matched to this one).

**Comment by MoArtis** [comment]
I copied the new upscaled texture in the full and 1.1 folders. 

I do not have a good save to test it though. :)

**Comment by Kayael76** [comment]
I'll try it tonight, no problemo ! Thanks !

**Comment by Kayael76** [comment]
It works perfectly !
