### ISSUE TITLE
BG mismatched in 56 - Nemesis fight

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#111]
Bad tex1_640x480_8c1445fd28ee8617_5

![tex1_640x480_8c1445fd28ee8617_5](https://user-images.githubusercontent.com/48800201/59951588-b4654480-9479-11e9-8eef-c73ef3fb5f58.png)

The good one is :

![tex1_640x480_8c1445fd28ee8617_5](https://user-images.githubusercontent.com/48800201/59951622-ccd55f00-9479-11e9-8a8f-c710c6f90e57.png)

R30D05 is already associated to the good texture. Odd.

**Comment by MoArtis** [comment]
![image](https://user-images.githubusercontent.com/3904610/60332357-3ea52f80-99c9-11e9-815f-605647cbcff3.png)

Basic mismatch. Now we have to find the room id of that non destroyed version.

**Comment by Kayael76** [comment]
non destroyed is R30305, no duplicates.

**Comment by MoArtis** [comment]
tbt

**Comment by Kayael76** [comment]
Still not fixed

**Comment by MoArtis** [comment]
Something is wrong then. Can you try to share a savestate just before the thing explode?
I know it's not supposed to work but let's give it a try.

**Comment by MoArtis** [comment]
🙃
![image](https://user-images.githubusercontent.com/3904610/60385827-8195fe80-9ac0-11e9-8216-54d90042412e.png)

**Comment by Kayael76** [comment]
Non detroyed is actually R30305, haha. My brain is melting.

**Comment by MoArtis** [comment]
tbt again @Kayael76 with the pack currently in gdrive

**Comment by Kayael76** [comment]
Ok it's working correctly now 👍
