### ISSUE TITLE
BG mismatched in 24 - Front City Hall

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#113]
The bad tex1_640x480_e5347aa1b97b6470_5

![tex1_640x480_e5347aa1b97b6470_5](https://user-images.githubusercontent.com/48800201/59954193-c0560400-9483-11e9-8bf8-0f21d3f351ac.png)

The good one is :

![tex1_640x480_e5347aa1b97b6470_5](https://user-images.githubusercontent.com/48800201/59954210-d2d03d80-9483-11e9-86ab-2d5c1fba9200.png)

It should be matched with R20701 which is not present in the PC named upscales, thus the upscaled mask is missing too (it's added in my update folder, under New masks to match).

**Comment by MoArtis** [comment]
tex1_256x256_946a83b523425310_189f2d6772245910_9 (I'm just putting the mask name I got from playing, just in case 😉)

**Comment by MoArtis** [comment]
Serious question: why using the one without details in the shop?

**Comment by MoArtis** [comment]
And I'm not so sure what I'm supposed to do here.

**Comment by MoArtis** [comment]
The current situation: I have one BgInfo matched to the GC bgs and masks for the two versions of the BG. I'm missing the upscaled version BG for R20701 but still the BG is displayed upscaled in game.
SO there is another Room ID matched with the same GC names. Apparently: R2070B

**Comment by Kayael76** [comment]
It's a case of window intact / window broken, that's why you see more details. But the first times pass through here, the window is intact. Enemies (dogs or crows, that's random) break through at some point. So the BG switch entirely at this point (there's two distinct GC dumps for those BG).

**Comment by MoArtis** [comment]
Ok it should be alright now. Tbt.

**Comment by MoArtis** [comment]
Fixed
