### ISSUE TITLE
R30B12 wrong mask displayed

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#114]
Like R21200, probably because it's almost entirely black.

The good tex1_256x256_$_a89f936bd4e1dbdb_9 : 

![tex1_256x256_$_a89f936bd4e1dbdb_9](https://user-images.githubusercontent.com/48800201/59964902-7f9fce80-9507-11e9-9156-67fac3a11d34.png)

Other duplicates might be involved

**Comment by MoArtis** [comment]
tbt again @Kayael76 with the pack currently in gdrive. Pretty sure you can found and test that one faster than me. 😂

**Comment by Kayael76** [comment]
I donfirm it's fixed !
