### ISSUE TITLE
Bad DDS Format on texts

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#116]
![GLEE08-2](https://user-images.githubusercontent.com/3904610/59971352-0fe41f00-95ad-11e9-82b3-c171af07bcb7.png)

The texts of the files are currently compressed using BC7 which cause transparency issues.

**Comment by MoArtis** [comment]
Strangely RE2 is also using BC7 for the file's texts and they don't have that issue. 🤔 We need to investigate the cause.

**Comment by Kayael76** [comment]
I did the texts a while ago fo the first pack before we worked together, I may have used different settings, maybe even compressed the final output but I don't remember. I noticed that too and ran the files through Affinity, the updated PNG are in the GLEE08 folder, it might have fixed the transparency issue.

**Comment by MoArtis** [comment]
Seems fixed! 👍 If specific files feature the issue, we will create a dedicated issue for each one of them.
