### ISSUE TITLE
Suggestion to upscale or replace the fire hydrant

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#119]
![tex1_256x256_290aac866bdbe552_657f975e37e7591f_9](https://user-images.githubusercontent.com/3904610/59972058-b1be3880-95ba-11e9-8ede-a1ce0aa8e217.png)

![GLEE08-6](https://user-images.githubusercontent.com/3904610/59972067-cc90ad00-95ba-11e9-80fd-6be5100aad82.png)

**Comment by MoArtis** [comment]
This thing needs to wildcarded. Seems to be considered as a 3d model (I guess it is just one quad).

tex1_256x256_$_657f975e37e7591f_9

**Comment by Kayael76** [comment]
I did that, it's merged in GLEE08 and I put it in m update folder :

![tex1_256x256_$_657f975e37e7591f_9](https://user-images.githubusercontent.com/48800201/60336327-4f8d7b00-99a0-11e9-9084-2486d1cbc183.png)

Look better but still a bit unnatural.

**Comment by MoArtis** [comment]
It looks fine to me. Just hope the sharp black part on top is not visible in game.

**Comment by MoArtis** [comment]
![GLEE08-48](https://user-images.githubusercontent.com/3904610/60380080-c6df0f80-9a71-11e9-81d3-a5d19e1213eb.png)

The original asset is just not that great to begin with thus it really stands out from the background. There is no consistency between the two. 😂

But at least it is upscaled now and it should be good enough. 👍 Let's move on!
