### ISSUE TITLE
Mask Alternate TLUT hash - Room ID needed

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#125]
tex1_256x256_$_3116be8b75839f5c_9

Can also be found as

tex1_256x256_d20b409e5901f03e_f0719756c9133479_9

![tex1_256x256_d20b409e5901f03e_f0719756c9133479_9](https://user-images.githubusercontent.com/3904610/59972298-390dab00-95bf-11e9-96c9-370c63abada5.png)

![GLEE08-12](https://user-images.githubusercontent.com/3904610/59972308-6fe3c100-95bf-11e9-96b2-49f5f6edfd07.png)

**Comment by Kayael76** [comment]
It's R2110A

**Comment by MoArtis** [comment]
Seems fixed!
