### ISSUE TITLE
Mirrored Text (Thanks Capcom) - Room ID needed

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#126]
![GLEE08-13](https://user-images.githubusercontent.com/3904610/59972329-be915b00-95bf-11e9-86cd-9f06c98cb648.png)

Low priority and obviously the text on the texture doesn't correspond to the text displayed when the player interacts with the panel. 👍👍👍

**Comment by Kayael76** [comment]
Yes it's one of the BG I want to edit because it's clearly visible.

**Comment by MoArtis** [comment]
Oh shit I'm realizing my internet must have fucked up and didn't saved my comment at the time. I wrote the text written there.

Here it is:
We must channel our knowledge to the future.
For it shall always show us our greatest destiny.
Raccoon City Mayor, Michael Warren.

**Comment by Kayael76** [comment]
![R20509](https://user-images.githubusercontent.com/48800201/60036966-b9f89f80-96b0-11e9-97e1-451f4b12e98b.png)
![R20505](https://user-images.githubusercontent.com/48800201/60036968-b9f89f80-96b0-11e9-8559-0c926f6bb84b.png)

Available in RE3 Seamless HD Project\Kayael updates\061419\BG edits

**Comment by MoArtis** [comment]
Tested 👍
