### ISSUE TITLE
Investigate the R316 RDT file issue

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#128]

**Comment by Kayael76** [comment]
There's a duplicate at R30E11 so you might get BGinfo from here.

**Comment by MoArtis** [comment]
All good! There is a bug with the RDT converter for RE3 but I'm too lazy to dig into that spaghetti code. I just isolated that file, converted it and matched GC textures with them. Hopefully there is no other issue like that.
