### ISSUE TITLE
R11C01 multi-layer mask

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#132]
Not sure about this one but since it works the same way as the other 2, better be safe than sorry and check it out now.

![R11C01_altMaskSource](https://user-images.githubusercontent.com/48800201/60218679-54531180-9870-11e9-829f-4420a4db1b8a.png)

**Comment by Kayael76** [comment]
Same as R11C02, we can ignore it and keep the intact pipe just like it right now in the test pack.

**Comment by MoArtis** [comment]
![GLEE08-105](https://user-images.githubusercontent.com/3904610/60669996-3ace4d00-9ea2-11e9-86c8-81f7bf374130.png)
![GLEE08-104](https://user-images.githubusercontent.com/3904610/60669997-3ace4d00-9ea2-11e9-8798-9b72449b60f0.png)
Fixed! :)
