### ISSUE TITLE
Missing mask

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#133]
tex1_256x256_fda0aa5f236c3df5_03cd41488dfa2c76_9
![tex1_256x256_fda0aa5f236c3df5_03cd41488dfa2c76_9](https://user-images.githubusercontent.com/3904610/60282682-1b7f6f00-993a-11e9-8a48-5c1b97dc00da.png)

![GLEE08-41](https://user-images.githubusercontent.com/3904610/60282647-073b7200-993a-11e9-8f6e-d1bce54c68c7.png)

**Comment by MoArtis** [comment]
![GLEE08-43](https://user-images.githubusercontent.com/3904610/60282712-3225c600-993a-11e9-854d-f7be81df06ab.png)

**Comment by Kayael76** [comment]
Same as the other, the upscaled mask is present in GLEE08 : 

![tex1_256x256_$_03cd41488dfa2c76_9](https://user-images.githubusercontent.com/48800201/60283527-a3995080-9909-11e9-9f9c-6a16e4d84920.png)

But this BG too is part of the AMS needed.

**Comment by MoArtis** [comment]
As it's an AMS it's normal it was not generated in the latest pack. Let's close that and the other one.
