### ISSUE TITLE
Missing mask

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#134]
tex1_256x256_dbe7cced20873b62_ea2e4ef83bb01b13_9
![tex1_256x256_dbe7cced20873b62_ea2e4ef83bb01b13_9](https://user-images.githubusercontent.com/3904610/60282789-58e3fc80-993a-11e9-9b51-a6fd4f523f76.png)

![GLEE08-44](https://user-images.githubusercontent.com/3904610/60282821-6ac59f80-993a-11e9-958d-3bdeb65188c9.png)

![GLEE08-43](https://user-images.githubusercontent.com/3904610/60282827-6d27f980-993a-11e9-9a3a-c518585061d2.png)

**Comment by Kayael76** [comment]
Strange, the upscaled version is in GLEE08

**Comment by MoArtis** [comment]
So it's an AMS issue. For now the AMS are being skipped as expected. It would be better to test when the AMS are integrated.

**Comment by MoArtis** [comment]
Just in case the Room id is R12201
