### ISSUE TITLE
Missing Mask

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#135]
tex1_256x256_6a2e3fc7f2a4ab85_c8289cc445ac5558_9
![tex1_256x256_6a2e3fc7f2a4ab85_c8289cc445ac5558_9](https://user-images.githubusercontent.com/3904610/60283526-ec69fd00-993b-11e9-83d3-ced7cc66d27b.png)

![GLEE08-46](https://user-images.githubusercontent.com/3904610/60283536-f2f87480-993b-11e9-9c65-b5fa98fd9037.png)

**Comment by Kayael76** [comment]
This one gets me curious, do you know what you had in your inventory at this moment (did you grab the card on Brad or took the Jill's one, the blue gem, the STARS office key) ?

**Comment by Kayael76** [comment]
I've reproduced it if I go upstairs without the STARS key independently of everything else, it's just an overlook from my part (I remember clearly doing this because I noticed that, almost all RPD dumps would be with another tlut whether you have the key or not)

**Comment by MoArtis** [comment]
Fixed
