### ISSUE TITLE
Missing mask - R20D10 R20E01

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#136]
![GLEE08-55](https://user-images.githubusercontent.com/3904610/60380461-98186780-9a78-11e9-8b54-f8df849e4dbd.png)

The problem is simple. That BG got matched with R20D10, which doesn't have any mask data in its RDT. But since it seems to be a duplicate of R20E01, that last one got ignored completely thus we end up with backgrounds without mask data...

The tool should prioritize duplicates WITH mask data. . . 😡 Now it is very hard to know how many BG with a mask texture got matched with RDTs that don't feature mask data.

I really don't understand why the game have such duplicates though... dev data maybe?

**Comment by Kayael76** [comment]
I really couldn't say. There might be something tied to the mercenaries game, maybe just opening the iron curtain triggers a change in BG though they're the same. Or the cutscene that plays when the zombies are coming. We'd need to analyze the PC version and see what rooms are loaded to fully understand how the game works.

I guess that the first test version was pretty good because it was missing very few masks considering (if we put the mismatches aside)

This mask here was part of the missing ones I uploaded.

**Comment by Kayael76** [comment]
Oh shit yeah I think it's because of that cutscene with the zombies because it has no mask during it, so the game might call that BG with no mask data.

**Comment by Kayael76** [comment]
But the way I see it, if there's a mask rip, it means that this BG has mask data, right ? I miced the BG and masks rips together and indeed, you clearly see in the duplicates which ones have masks and which ones don't.

**Comment by MoArtis** [comment]
Like I said only R20E01 has mask data. But it got ignored during the RDT conversion as the tool already found R20D10 (which has no mask data) thus it ignored the duplicate.

But that's only because I assumed BG duplicates will have the same mask data. :<

**Comment by MoArtis** [comment]
You can blame everything on the dev team being pretty silly in term of bg/mask data. :D Why not just using the same damn data? I guess that's because the BG looks better without mask but still it seems like a wasteful amount of tweaks.

**Comment by MoArtis** [comment]
Oh in this case, I do have the data for the two version. But I don't have an upscaled version of the BG for R20E01. You certainly missed it as the duplicates are utterly confusing.

It's ok, I can just copy paste it.

**Comment by Kayael76** [comment]
Yeah on GC it's just an unique dump, so it's just a matter of matching it to the good duplicate.

**Comment by MoArtis** [comment]
Fixed!

![GLEE08-55](https://user-images.githubusercontent.com/3904610/60382508-82199f80-9a96-11e9-9937-eda4d0cf6fac.png)
