### ISSUE TITLE
R20D00 - Mirrored text

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#138]
Damn! that Room looks pretty good compared to the original one (thanks to these low res masks covering half of the room :D ).

It would be nice to fix the mirrored warning text. It could be perfect for the website too.

![GLEE08-59](https://user-images.githubusercontent.com/3904610/60382836-3b7a7400-9a9b-11e9-8040-4f9d72d407ce.png)

**Comment by Kayael76** [comment]
It appears on multiple BG of this area, I'll make a fix. But if you take a close look at what's written on the BG, you'll see that A LOT of them has mirrored text.

**Comment by MoArtis** [comment]
My theory is that they made the scene the other way around and then decided it flows better mirrored or something. Finally they couldn't be bothered fixing the text. :D
