### ISSUE TITLE
Missing Mask - R50A04 R50A0C

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#139]
tex1_256x256_3d7644f6cee31296_8ff6b0e4e4187bec_9
![tex1_256x256_3d7644f6cee31296_8ff6b0e4e4187bec_9](https://user-images.githubusercontent.com/3904610/60383273-5cde5e80-9aa1-11e9-8059-f1655aa404f0.png)

![GLEE08-64](https://user-images.githubusercontent.com/3904610/60383275-69fb4d80-9aa1-11e9-93f7-8a6b0924e7ce.png)

**Comment by MoArtis** [comment]
Also a case of a missing upscale for the duplicate (R50A04) @Kayael76 😰 Maybe I should stop tracking issue and check with you if you have a list of these missing upscales or something?

**Comment by MoArtis** [comment]
FIXED and the "Upscaled BGs" gdrive folder updated. But the missing textures issue still need to be solved.

**Comment by MoArtis** [comment]
One thing to mention: it's fixed but R50A0C has no gamecube mask dump while having a completely different mask texture and data. @Kayael76 Do you know why? could be unused / beta asset?

**Comment by Kayael76** [comment]
I have not a single clue. The 2 BG are identical so that's a mystery why there are 2 masks. Maybe related to Nicholai dead or alive and all the dialogue you can have with him. That wouldn't surprise me after all.

**Comment by Kayael76** [comment]
Well nope, it's the same mask all along, whatever scenario you play. 

The truth is out there 👽

**Comment by MoArtis** [comment]
ahah then fuck it
