### ISSUE TITLE
R11B01 missing masks

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#147]
It's one of the masks we can't wildcard, in the sales office. I took the liberty of duplicating and renaming an existing occurence, it's already in GLEE08. The mask names are : 

tex1_256x256_76439082fad357a8_e3c364c1425f893c_9
tex1_256x256_fad6f3d034bbae92_e3c364c1425f893c_9
tex1_256x256_39a864c0ffeb84c7_e3c364c1425f893c_9
tex1_256x256_4cb8dfdb0dc37988_e3c364c1425f893c_9
tex1_256x256_39038efb1a54223b_e3c364c1425f893c_9

We just need to match it manually.

**Comment by Kayael76** [comment]
It's a neverending shit, like the VFX. I hate that. Turn in circle in the room, you can end up with new dumps for no reasons (well, the paletted garbage is different but seriously, no reason for this shit to change)

**Comment by Kayael76** [comment]
I keep getting new dumps. It's unfixable I'm afraid.

**Comment by MoArtis** [comment]
![GLEE08-81](https://user-images.githubusercontent.com/3904610/60645181-9bda2e80-9e6a-11e9-9136-26bad09b74c3.png)
From a fully rebuilded pack. The unfixable got fixed! 😎 👍
