### ISSUE TITLE
R11B0A missing masks

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#150]
Like #147 

We need to match manually : 

tex1_256x256_139d148d01d7148e_e3c364c1425f893c_9
tex1_256x256_782bd26807587cc9_e3c364c1425f893c_9
tex1_256x256_c030b3e37505de1f_e3c364c1425f893c_9
tex1_256x256_ad944ad359b8431b_e3c364c1425f893c_9
tex1_256x256_64ce5b61809614b9_e3c364c1425f893c_9
tex1_256x256_1965a63f29a197c3_e3c364c1425f893c_9

I already made the duplicates in GLEE08

**Comment by Kayael76** [comment]
Neverending dumps. No way to properly fix that I'm afraid. Except if there's a way to force the game to use the same mask for these 2 BG. I wouldn't hold my breath here.

**Comment by MoArtis** [comment]
![GLEE08-80](https://user-images.githubusercontent.com/3904610/60645101-633a5500-9e6a-11e9-89c0-756903ef99dc.png)
 Fixed! 🎉
