### ISSUE TITLE
R2070B - no mismatch but calling 2 BG

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#152]
![R2070B](https://user-images.githubusercontent.com/48800201/60390499-50c1c380-9ad8-11e9-976c-5234602f3f6e.jpg)

The good one is displayed but there's still this thing with 2 BG.

**Comment by MoArtis** [comment]
Pay attention. Your texture folder has no impact on the OSD. You can ignore it most of the time. Otherwise it will require me to develop a very complex system on top of dolphin's texture replacement system.

So don't assume bugs from the OSD. I will rebuild it from time to time though. :)

**Comment by Kayael76** [comment]
Yeah but why does it do this ? Does it use R2070B as BG diplayed but bginfo from R20701 ?

**Comment by MoArtis** [comment]
The two BgInfos used to use the same GC BG texture hashes due to the mismatch. So when Dolphin is pulling that texture hash, my hack basically finds two correspondences and display them.
