### ISSUE TITLE
R12406 wrong mask displayed

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#153]
![r12406](https://user-images.githubusercontent.com/48800201/60457933-951aa400-9c3d-11e9-9200-a01dfaec57ce.jpg)

It was working before, but I recognize the BG source of this mask, it's R3160E or R31601 (or maybe R30E0E).

The good tex1_256x256_$_bb4e0c2e3b9822ce_9

![tex1_256x256_$_bb4e0c2e3b9822ce_9](https://user-images.githubusercontent.com/48800201/60458436-e70ff980-9c3e-11e9-918b-49fad9a498ca.png)

**Comment by MoArtis** [comment]
That's crazy mismatch. It would be nice to understand what happened. The tool cannot do such a bad mismatch. 🤔 Like the rail Canon, it was just a naming issue.

**Comment by MoArtis** [comment]
![GLEE08-83](https://user-images.githubusercontent.com/3904610/60645551-8added00-9e6b-11e9-813c-e6d3f9a2dc1b.png)

Fixed! but the cause of that bug remains a mystery. 🤔 Whatever and let's move on.
