### ISSUE TITLE
R30E0A AMS doesn't work

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#154]
It's a standard AMS. Might be tied to R3160A like the OSD says.

![R30E0A](https://user-images.githubusercontent.com/48800201/60460577-69e78300-9c44-11e9-9582-52d85f07b19c.jpg)

Might need only to rename the AMS accordingly.

**Comment by MoArtis** [comment]
I played the scene with and without the pack. It seems fine to me. You might want to have a second look in the future but I guess we are done with this one too.

![GLEE08-95](https://user-images.githubusercontent.com/3904610/60647798-20c84680-9e71-11e9-8377-920c2d9159fe.png)
