### ISSUE TITLE
AMS R3010A and R30109 mix up

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#157]
This one is on me, in fact those 2 BG don't neeed AMS, it's other ones : 

R30F06 and R30F07

I updated the AMS final folder and AMS ready for process folder accordingly (standard AMS)

**Comment by MoArtis** [comment]
Nemesis breaking the door:
![GLEE08-90](https://user-images.githubusercontent.com/3904610/60647511-7b14d780-9e70-11e9-874b-e45f92afa7ae.png)
![GLEE08-89](https://user-images.githubusercontent.com/3904610/60647515-7bad6e00-9e70-11e9-9fe3-a66f75085cee.png)

Arriving before the Nemesis:
![GLEE08-93](https://user-images.githubusercontent.com/3904610/60647636-b1eaed80-9e70-11e9-8e63-95986088486c.png)
![GLEE08-94](https://user-images.githubusercontent.com/3904610/60647637-b31c1a80-9e70-11e9-9e88-8d6894206296.png)

I guess we are done with this one. Hopefully?
