### ISSUE TITLE
R10F01 multilayer mask

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#159]
![R10F01](https://user-images.githubusercontent.com/3904610/60672440-f0e86580-9ea7-11e9-8e16-997c8e1c9e06.png)
![R10F01_altMaskSource1](https://user-images.githubusercontent.com/3904610/60672421-e037ef80-9ea7-11e9-8b9f-1585716b8454.png)
![R10F01_altMaskSource2](https://user-images.githubusercontent.com/3904610/60672423-e0d08600-9ea7-11e9-8c3d-42be38448763.png)

![R10F01_mask](https://user-images.githubusercontent.com/3904610/60672467-fe055480-9ea7-11e9-8ab7-cf7292e97489.png)

**Comment by MoArtis** [comment]
![GLEE08-128](https://user-images.githubusercontent.com/3904610/60700448-89272e80-9f2a-11e9-9da7-5ee4994680d3.png)
![GLEE08-129](https://user-images.githubusercontent.com/3904610/60700449-89272e80-9f2a-11e9-8c81-278b892f8634.png)
Seems fixed! But I don't know how to check the "CLOSED" case. So I keep that one in TBT. :)

**Comment by Kayael76** [comment]
You can try (if you don't wanna wait) with Action Replay code to have the boutique key in crate, then from a fresh new game you can go to the boutique. Since no costume are unlocked, all closets should be closed !

**Comment by MoArtis** [comment]
![GLEE08-135](https://user-images.githubusercontent.com/3904610/60750876-3ceaf580-9fe1-11e9-9aef-a4bc9f4dc17f.png)
Good tip! Thanks!
And we are done with this one too. :)
