### ISSUE TITLE
R20F13 - Press office 2nd floor - Window mess

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#160]
**Pre Nemesis**
Original:
![GLEE08-120](https://user-images.githubusercontent.com/3904610/60678853-65c39b80-9eb8-11e9-8f21-3f90eec0a266.png)
Pack:
![PRENEMESIS](https://user-images.githubusercontent.com/3904610/60678884-76741180-9eb8-11e9-9fd3-446ee6af9ef4.PNG)

**Post Nemesis**
Original:
![GLEE08-118](https://user-images.githubusercontent.com/3904610/60678903-8be93b80-9eb8-11e9-83c0-1debebdc3366.png)
Pack:
![POSTNEMESIS](https://user-images.githubusercontent.com/3904610/60678910-94417680-9eb8-11e9-9ba8-74ae7848eebe.PNG)

Apparently the two rooms are wrongly using the same GC bg name. I can fix that.
Also @Kayael76 are you noticing that the pre-nemesis shot implies that the window is using a full frame but WITH broken glasses. It would make so much more sense than the pink glass panes or the fully transparent / no glass panes one... :) But that's a lot of work.

**Comment by MoArtis** [comment]
Maybe keeping the frame without any glass and of course the full frame would be a good balance of consistency and work. No matter you decide to edit out the pink glass panes from these other rooms or not.

For this particular room, I would recommend that: keeping the pre nemesis room as is. And just fixing the post nemesis room mismatch. Less work, less headache.

**Comment by Kayael76** [comment]
I think R20F13 might be missing the good upscale, it should be the destroyed window in the PC rips right ? I'll provide the good upscale when I'll be back home. Let's keep this open for now.

**Comment by Kayael76** [comment]
Here it is : 

![R20F13](https://user-images.githubusercontent.com/48800201/60770892-650d4e00-a0e0-11e9-85e3-d96f17e5a097.png)

I'm also putting it in Upscaled BG.

**Comment by MoArtis** [comment]
![GLEE08-165](https://user-images.githubusercontent.com/3904610/60771372-bd147680-a119-11e9-8dbd-dfc4e6481a7d.png)
![GLEE08-166](https://user-images.githubusercontent.com/3904610/60771373-bd147680-a119-11e9-8a5e-96ed2110b9cd.png)
Seems to be working. Good job! 👍

**Comment by Kayael76** [comment]
That shit is an AMS : the BG is always R20F13and R20F02 should be the AMS then. Pre Nemesis now shows this : 

![GLEE08-35](https://user-images.githubusercontent.com/48800201/60772952-c68fe580-a0fd-11e9-975c-a2ba88df1e8f.jpg)

when it should be like this : 

![GLEE08-36](https://user-images.githubusercontent.com/48800201/60772946-ae1fcb00-a0fd-11e9-988d-e02bed151f0e.jpg)

I'm updating the AMS folder then.

**Comment by MoArtis** [comment]
Good catch! Let me fix this shit.

**Comment by MoArtis** [comment]
So only R20F13 is an AMS, right?

I only processed R20F13, and here are the results:

Pre-fight:
![GLEE08-176](https://user-images.githubusercontent.com/3904610/60785528-e7038280-a185-11e9-8335-a1f78e1e00b4.png)
![GLEE08-177](https://user-images.githubusercontent.com/3904610/60785531-e79c1900-a185-11e9-94e8-c8ab8c25e6a6.png)

Post-Fight Hidden:
![GLEE08-173](https://user-images.githubusercontent.com/3904610/60785656-4a8db000-a186-11e9-8a92-f0ecb641cc8f.png)
![GLEE08-172](https://user-images.githubusercontent.com/3904610/60785658-4a8db000-a186-11e9-96c3-e3b8c9165e2e.png)

Post fight NOT hidden:
![GLEE08-168](https://user-images.githubusercontent.com/3904610/60785612-1fa35c00-a186-11e9-8ff7-4696d250b222.png)
![GLEE08-169](https://user-images.githubusercontent.com/3904610/60785613-203bf280-a186-11e9-9b18-8ab958658468.png)

Post Jump out of the window:
![GLEE08-174](https://user-images.githubusercontent.com/3904610/60785555-fda9d980-a185-11e9-9c72-5b72f1a1cf65.png)
![GLEE08-175](https://user-images.githubusercontent.com/3904610/60785557-fda9d980-a185-11e9-8e7c-a1c2deadcc3e.png)

**Comment by MoArtis** [comment]
hum the post fight hidden looks pretty bad. 🤔 Something is wrong.

**Comment by MoArtis** [comment]
After some investigations, I guess that the culprit is the current processed AMS for R20F13.

It's missing the broken glass parts. It should looks something like that:
![R20F13_altMaskSource](https://user-images.githubusercontent.com/3904610/60786250-6003d980-a188-11e9-8e34-b923cc53258a.png)

**Comment by Kayael76** [comment]
I cedited the AMS in its folder ready for process. I hope it's alright this time 🤞

**Comment by MoArtis** [comment]
![GLEE08-268](https://user-images.githubusercontent.com/3904610/60800619-175c1880-a1a8-11e9-840d-6c5753cc813f.png)
It's working and it looks great! We are done here. :)
