### ISSUE TITLE
R21801 mask problem

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#162]
It's one of the rooms where we cant' wildcard the mask.

![r21801](https://user-images.githubusercontent.com/48800201/60772640-bbd35180-a0f9-11e9-8e21-4c2afafdce46.jpg)

The mask can have 2 different tlut : 338ef6c05709e506  or 91fbb229c7fa0f59. That is also the case for R21807. Of course the masks are unique for each room.

I guess you have updated Dolphin on the Gdrive so I should have the latest version.

**Comment by MoArtis** [comment]
![image](https://user-images.githubusercontent.com/3904610/60782749-730fad00-a17a-11e9-8f69-b20a6564d25a.png)
A simple overlook in my code when 2 shared TLUT are involved. Should be fixed now but TBT. 😃

**Comment by MoArtis** [comment]
I guess I tested the thing enough. Closing this one too!
