### ISSUE TITLE
Dolphin freezing after the first door animation in RE3

### ISSUE THREAD

**Issue by mrbaungartner** [MoArtis/ResidentEvilSeamlessHdProject#163]
After the first door animation the game freezes in a black screen.
At the demo of Jill's gameplay the following error occurs:  MapTexelBuffer Failed in d:\projects\residentevilseamlesshdproject\dolphinreshdp\source\core\videobackends\d3d\vertexmanager.cpp at line 146: Map texel buffer
How can i solve this?

**Comment by MoArtis** [comment]
Try to untick "GPU Texture decoding" in Graphics => Hacks.
Let me know if it works for you.

**Comment by mrbaungartner** [comment]
> Try to untick "GPU Texture decoding" in Graphics => Hacks.
> Let me know if it works for you.

I already tried this, but nothing.

**Comment by MoArtis** [comment]
Great news! 👍 Have a nice day!
