### ISSUE TITLE
Some backgrounds are only half reconstructed mask textures!

### ISSUE THREAD

**Issue by MarcosBaungartner** [MoArtis/ResidentEvilSeamlessHdProject#165]
I realized that some parts only half are reconstructed in HD, like this:

![RE3](https://user-images.githubusercontent.com/21061990/61312398-bac3b380-a7ce-11e9-99f0-21698f2223ca.JPG)

**Comment by Kayael76** [comment]
Hello and thank you for reporting ! This issues has already been identified and will be fixed in the future update. Don't hesitate to share anything else, it might not have been reported yet. 👍

**Comment by mrbaungartner** [comment]
Sometimes some parts doesn't reconstruct, same with Jill's portrait in the inventory screen:
![Capturar](https://user-images.githubusercontent.com/21061990/61431464-f14f1a80-a903-11e9-9188-a850f1e69450.JPG)

The Director's Diary has the word "bhecome":
![Capturar2](https://user-images.githubusercontent.com/21061990/61431500-0e83e900-a904-11e9-9242-50d3e2cb48d0.JPG)
