### ISSUE TITLE
Sherry's pendant is featuring compression artifact

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#166]
![image](https://user-images.githubusercontent.com/3904610/61491274-2c5a5800-a9af-11e9-87ce-48bb0cde4833.png)

We certainly just need to replace the two textures with Sherry's pendant with ones using BC3 instead of BC7 texture format.

Here are the new textures:
Link removed - We need to properly convert the png files to DDS BC3

**Comment by MoArtis** [comment]
tex1_256x256_$_989f237c9393b980_9.DDS
tex1_256x256_$_0577060f990bb4f1_9.DDS

**Comment by Napper64** [comment]
[Sherry_pendant.zip](https://github.com/MoArtis/ResidentEvilSeamlessHdProject/files/3965430/Sherry_pendant.zip)

These texture files don't contain the artifacts. I converted the PNG's to DDS(BC1 Linear). I still had the compression artifacts when i converted to BC3

**Comment by Kayael76** [comment]
Thanks Napper, that will be handy !
