### ISSUE TITLE
textures do not work

### ISSUE THREAD

**Issue by michel1223** [MoArtis/ResidentEvilSeamlessHdProject#169]

**Comment by Napper64** [comment]
Hi Michel,

This is not the place to report personal troubleshooting issues. This is to record issues in the actual source control. So please do close this and report issues in http://re123.bplaced.net/board/viewtopic.php?f=22&t=591

To help with your problem. All you need to do is download the "1.1 Full Pack" from https://www.reshdp.com/re2/#customized-dolphin-build

Then once extracted. 
Open that custom Dolphin Build.
Go to "Graphics Config"
Go to "Advanced" tab
Select "Load custom textures"

And that's it. You can press the "DELETE" key during gameplay to switch between old and new textures. 

I hope that helps!

**Comment by MoArtis** [comment]
@michel1223 Make sure you are using an US/NTSC version of the games. Join us on Discord if you need more help: https://discord.gg/HCZWV6q

@Napper64 Thanks for the help. :)
