### ISSUE TITLE
I downloaded the simulator. Also downloaded the compressed package, why can't I run the game?

### ISSUE THREAD

**Issue by 13803453009** [MoArtis/ResidentEvilSeamlessHdProject#170]
![2345截图20190906031613](https://user-images.githubusercontent.com/54958235/64372175-d9b72700-d054-11e9-938f-a0d609f9ec7c.png)
I want to know what way to run the game, thank you!

**Comment by MoArtis** [comment]
As indicated you need to double click on the middle of the window and select the folder where the game's ISO file is located.
For obvious legal reason, the ISO file is not included and we will not help you to get your hands on it. :)

**Comment by 13803453009** [comment]
Thank you very much for your answer! But where do I know where to get ISO files?

**Comment by MoArtis** [comment]
Like I said, we will not discuss about Piracy here, on Discord or anywhere else. You have to find the ISO files by yourself. Thank you!
