### ISSUE TITLE
A well maintained CONTRO room

### ISSUE THREAD

**Issue by wesker265** [MoArtis/ResidentEvilSeamlessHdProject#171]
This mispelling of "control room" has been present in every release of Resident Evil 3. I was hoping that the SHDP team can fix this.

Thank You!

![Annotation 2019-09-12 171630](https://user-images.githubusercontent.com/45540160/64874172-5c188b80-d5ff-11e9-9be4-71a7b535717c.png)

**Comment by Kayael76** [comment]
Same as #172, there's no way to distribute an iso patch that would modifiy the correct data file.
