### ISSUE TITLE
Improper Ammo Terms

### ISSUE THREAD

**Issue by wesker265** [MoArtis/ResidentEvilSeamlessHdProject#172]
Is the SDHP team able to change the improper ammo terms used by Capcom in RE2 and RE3?
For example "DOT380 rounds" should be ".380 ACP rounds".
The Desert Eagle also says "DOT50A.E." instead of ".50 AE"

**Comment by Kayael76** [comment]
Unfortunately no, this kind of mistake would need to edit a source data file and there's no proper way to distribute an iso patch.
