### ISSUE TITLE
menu sound / documents

### ISSUE THREAD

**Issue by GhostBullet217** [MoArtis/ResidentEvilSeamlessHdProject#173]
(RE2) This game is amazing, Awesome job. i found 2 minor glitches. 1st is on the menu. the sound pops from time to time. 2nd when your reading the documents, the bottom is some-what cut off and after you get to the end of the document, you can keep scrolling instead of the document stopping at the end. I love this game, you guys did an amazing job.

**Comment by MoArtis** [comment]
Thank you for the nice message and for playing the mod!

Please, can you send us a screenshot of the cut off document? (You can drag and drop or use the print screen key then CTRL+V inside a new comment)

For the sound, there is nothing we can do. It's an emulation and / or a performance issue. 😀

**Comment by Kayael76** [comment]
The doc glitch sounds like you might have the "unlock all files" cheat active ?
