### ISSUE TITLE
Hospital Save Room Melting RE3

### ISSUE THREAD

**Issue by Asmerith** [MoArtis/ResidentEvilSeamlessHdProject#174]
Greetings
 
So far the Seamless HD has been great but I have noticed extreme melting on the item box and most of the Hospital saveroom in RE3. Don't know if this has been reported but I thought I'd just point it out if it was missed. Please see attachments for screenshots.

Kind Regards

![GLEE08-2](https://user-images.githubusercontent.com/56228922/66271848-fd8fa780-e862-11e9-8541-6f6200cf6ac8.png)
![GLEE08-1](https://user-images.githubusercontent.com/56228922/66271808-c3260a80-e862-11e9-9bd1-81de477fed1e.png)

**Comment by Kayael76** [comment]
Hello and thanks for reporting !

This room and a few others don't have 640x480 sources but only 320x240, hence the murkier look. Sadly there's nothing much we can do on our end. I hope you'll keep enjoying the mod !

**Comment by Asmerith** [comment]
> Hello and thanks for reporting !
> 
> This room and a few others don't have 640x480 sources but only 320x240, hence the murkier look. Sadly there's nothing much we can do on our end. I hope you'll keep enjoying the mod !

No problem, it is only something minor and this Seamless HD mod is so amazing that it doesn't even matter. You guys have done a magnificent job and I thank you for all your hard work. Bringing these games to HD really helps with their preservation and it has been a joy to play them again. Can't wait to see what you guys do with RE1.

**Comment by Kayael76** [comment]
That's very much appreciated, thank you !
