### ISSUE TITLE
Multi-language?

### ISSUE THREAD

**Issue by Flag-King** [MoArtis/ResidentEvilSeamlessHdProject#175]
Hi there;

I'm searching for some contact with the team RESHD but I can't found it.
Do you have any project about multi-language in your RESHD works? 
Please contact me if you want it. We are from CT-STARS. We translated to brazilian portuguese almost all of the RE games to PC and Playstation versions.

Best;

Flag
ct-stars.com

**Comment by Kayael76** [comment]
Hi and thanks for reaching to us !

We don't have any plan for localizations, the project was big enough so NTSC-US version made sense as an universal version.
Modding a GameCube iso is not an easy task, you can of course use the method we did and edit the textures themselves, but a lot of things in the game won't be translated this way (only the docs and menus can be translated like this, US versions don't have subtitles and everything else like item or background description is actually hardcoded).
Someone in the PT-BR community already did it that way : https://twitter.com/deadmat94/status/1204795476253564933?s=20

Alternatively, you can use the PAL versions of the game and translate the textures from this version (they have subtitles as textures if I'm not mistaken), the base language would be spanish though for the "un-translatable" things.

You can also try to modify the hardcoded text in the iso files and earn our total respect if you manage to do it haha :D

**Comment by Flag-King** [comment]
Hi. Thanks to fast reply;

We already translated the PC version of Resident Evil 3 to PT-BR in 2009 [Wow 10 years ago. I'm feellin older now... lol].
I just need to know if you authorize my group to realocate our PT-BR version to your GC version.

Best;


Flag
CT-STARS

**Comment by Kayael76** [comment]
No problem, you can absolutely do it. Cheers !
