### ISSUE TITLE
Game saves not showing up

### ISSUE THREAD

**Issue by daquen** [MoArtis/ResidentEvilSeamlessHdProject#177]
I just started playing the RE3 HdProject and if I save the game and die, I'm able to reload my save just fine, but once I close down Dolphin and relaunch it the saves are no longer there, forcing me to replay from the beginning each time. Is there a way to fix this?

**Comment by MoArtis** [comment]
Hello! Are you talking about the in-game saves (the typewriter) or Dolphin's save states (SHIFT + F1-F8) ? My guess is that you don't have write access on the folder where you installed the Dolphin / the pack.
Try to launch Dolphin as administrator.

**Comment by daquen** [comment]
I can't seem to figure out how to run Dolphin as admin. When trying to follow Google results there is no option to run as admin. I'm using winrar to open the file, I'm able to run winrar as admin and all other of my other desktop apps, but not this one. Also, I guess I'm talking about both save states as when I open Dolphin I have to reconfigure my graphics and controller layout. When in-game my typewriter saves are no longer there. I'm not the best with computers so maybe im missing something small, but I've tried everything. Attached is a photo of the options I get when right-clicking on Dolphin trying to run as admin.
![Capture 1](https://user-images.githubusercontent.com/59676024/72113227-d6d38800-330d-11ea-8cd9-64512094eee8.PNG)

**Comment by Kayael76** [comment]
You're launching Dolphin directly from the zip file ? Unpack the whole zip first, preferably in a folder not asking for admin rights (like My documents, avoid Program Files and such). If you don't unzip the whole thing, it sure can't save any configuration or memory card.

**Comment by daquen** [comment]
Thank you so much it works now. Sorry for bothering you with such a small and simple issue.
