### ISSUE TITLE
Error messages: Maptextelbuffer failure

### ISSUE THREAD

**Issue by Arkzil** [MoArtis/ResidentEvilSeamlessHdProject#178]
As the title says, I get that error message when moving between some specific screens
if I have it ignored everything seems to run as normal, but the nemesis selection parts will have a black screen over them; Including a screenshot of the error message (well, one of them at the least)
![photo_2020-01-13_12-12-59](https://user-images.githubusercontent.com/59835699/72267052-26f86600-35fe-11ea-8be7-f4acda462764.jpg)

**Comment by Kayael76** [comment]
You should try another video backend under the Graphics>General tab. Can you also post your PC spec in case that doesn't solve the issue ? Thanks.

**Comment by Arkzil** [comment]
Setting it vulkan fixed the error messages and the black screens on the selection scenes, but made the game stutter horribly on FMV and just generally run slightly slower

Pc speces are:
Geforce GTX 960
12 gb of memory
intel core i5 4460
Resolution is 1600 x 900, though I am running the game on a lower resolution

**Comment by Kayael76** [comment]
The GTX960 has only 2Go of VRAM, which might be a bit short. Can you check under Graphics>Hacks that GPU texture decoding is unchecked ? Also OpenGL as a video backend could boost performance in your case.

**Comment by Arkzil** [comment]
it was checked, unchecking it fixed it all
thanks for the help.

**Comment by Kayael76** [comment]
Ok perfect, hope you'll enjoy the mod !
