### ISSUE TITLE
shopping district revers door plates

### ISSUE THREAD

**Issue by Tantalus-X** [MoArtis/ResidentEvilSeamlessHdProject#179]
RE3
there are some doors where the text is reversed can you fix ?

**Comment by MoArtis** [comment]
Can you share a screenshot? But it's probably just the game using the same texture but flipped when using the door in one way or another. In that case, there is nothing we can do as flipping the texture will fix it one way but also flip the other way around. 😁

**Comment by Tantalus-X** [comment]
yes is thes ^^ ok is is therefore not to Fixed

**Comment by MoArtis** [comment]
This might be moddable on Classic Rebirth but sadly not on the Gamecube version using Dolphin. :D Thanks for the message anyway! Have a good day!
