### ISSUE TITLE
broken Color code in the box

### ISSUE THREAD

**Issue by Tantalus-X** [MoArtis/ResidentEvilSeamlessHdProject#180]
have found next problem ^^

the  Color code in the box Missing red
![GLEE08-1](https://user-images.githubusercontent.com/31192532/72683834-6f6ec280-3adb-11ea-96a2-a5b9ed200b34.png)

**Comment by Kayael76** [comment]
It's been reported, it's a bug from the GameCube version so nothing we can do here. It just doesn't display the good color. Thanks for reporting though !
