### ISSUE TITLE
Black screen during first Live Selection

### ISSUE THREAD

**Issue by LawAgent** [MoArtis/ResidentEvilSeamlessHdProject#185]
Hi!

Been loving the mod and finding it close to perfect, so forgive me if this seemingly small issues niggles me, haha!

Basically, when I go to the RPD and get the first Live Selection scene with Nemesis, the moments, where the image goes "inverted" or "negative", it goes black. Any idea what could be causing this? I'm a novice with emulating, so I have not fiddled with any settings.

Many thanks in advance,
Lauri

**Comment by Kayael76** [comment]
Hi, and thank you for your kind words !

Can you post your PC specs CPU and GPU please ? It looks like a backend issue, so when Dolphin is open, you should try Graphics and change the Backend here.

Let us know if it's still not working.

**Comment by LawAgent** [comment]
Hi again!

Thank you so much for the quick response! That did indeed fix it!

Thanks you once again and be sure to stay safe during these crazy times!

**Comment by berserkingyadis** [comment]
What was the backend that had the issue and which one fixed it?

**Comment by LawAgent** [comment]
It was Direct3D 11. OpenGL and Vulkan worked no problem!

**Comment by Kayael76** [comment]
Alright, perfect ! I hope you'll enjoy the mod. If you experience any new issue, feel free to open a new one or join us on Discord.
