### ISSUE TITLE
FPS drop on RE2 HD dolphin

### ISSUE THREAD

**Issue by George9711** [MoArtis/ResidentEvilSeamlessHdProject#187]
Hey, I've been experiencing some problems with the RE2 HD dolphin emulator, everytime there's a change of camera, open a door or there's a loading scene, the FPS drop drastically. I'd like to know what do I have to do to fix this problem or what files do I have to download to make it work right.
Thanks!

**Comment by MoArtis** [comment]
Hello!

If you own an SSD, try to put everything in there.
If not, you can try using "custom texture prefetching" in Graphics => Advanced.

If nothing helps then you are just experiencing the minimum latency of the gamecube when fetching data from the disc (which happens every time the background is changed).
For that, I have been told that "Speed up disc transfer rate" helps a lot on RE2 (not so much on RE3). Please note that It will make the FMV stutter though.

To enable that, right click on the game in Dolphin's main window, properties and that option should here:
![image](https://user-images.githubusercontent.com/3904610/80899202-07698280-8d40-11ea-9816-83a1d9167513.png)
