### ISSUE TITLE
Constant stuttering?!?? 

### ISSUE THREAD

**Issue by clay544888** [MoArtis/ResidentEvilSeamlessHdProject#188]
I've tried every solution here such as turning on "Prefetch Custom Textures" and even going to the RE2 and RE3 ISO's properties settings and enabling "Speed up disc transfer rate" and nothing! Both RE2 and RE3 stutter like crazy whether I'm going to in game menu's or every time the scene changes and it's maddening! I really want to play these beloved classics in pure HD and I can't because of the constant stuttering! Any suggestions!?!??

**Comment by MoArtis** [comment]
I'm guessing you are talking about the micro-stuttering when the background change but realistically it seems impossible to completely remove it on the console ports of these games, even with an emulator.
You are used to the PC version, right? How bad is the stuttering? Can you share a video of the problem?
