### ISSUE TITLE
Resident Evil 1 release date

### ISSUE THREAD

**Issue by 881z113** [MoArtis/ResidentEvilSeamlessHdProject#191]
When is Resident Evil 1 coming out? I periodically visit the site and see Stay tuned there. Can I find out the release date?

**Comment by Kayael76** [comment]
There's no ETA yet, there's a patch coming for the PC version that will allow us to use HD textures (no version of the game supports HD textures for now), but this patch has no ETA either since it's not done by us.

**Comment by vantablack333** [comment]
> There's no ETA yet, there's a patch coming for the PC version that will allow us to use HD textures (no version of the game supports HD textures for now), but this patch has no ETA either since it's not done by us.

It is now possible to replace textures in DuckStation. Why don't you use PSX version instead of the PC?

**Comment by Kayael76** [comment]
Duckstation textures replacement is buggy on a lot of games and the Resident Evil series is part of it.

**Comment by vantablack333** [comment]
Stenzek is a very talented person. If it is the case, he will fix it sooner or later. Just consider it as an option.

**Comment by Kayael76** [comment]
We did and we will eventually but chances are the PC version will be available much earlier.
