### ISSUE TITLE
White sqaure invisible on black/white cog puzzle to drain water.

### ISSUE THREAD

**Issue by D1g1talShaman** [MoArtis/ResidentEvilSeamlessHdProject#192]
Has anyone else had this problem? The white square to select the black/white cogs is missing. I was able to solve the puzzle without it but it took longer.

**Comment by Kayael76** [comment]
Looks like you're unlucky, you're the only one to report this and I haven't seen this problem before or on any videos from YT I checked. Have you changed any settings ? Do you have inventory texture dissapearing ? Might be a texture cache issue. It would be helpful if you posted your PC specs also. Thanks.

**Comment by D1g1talShaman** [comment]
> 
> 
> Looks like you're unlucky, you're the only one to report this and I haven't seen this problem before or on any videos from YT I checked. Have you changed any settings ? Do you have inventory texture dissapearing ? Might be a texture cache issue. It would be helpful if you posted your PC specs also. Thanks.

I changed graphs settings to Open GL and Auto. I also checked prefetch custom textures because the background changes were a little slow. I did not have problems with items disappearing but I did on the normal emulator. (usually heal sprays but opening and closing the inventory screen makes them reappear). I have an inspiron 15 dell laptop. (5000 series). Thanks for the reply.

**Comment by D1g1talShaman** [comment]
Update: Changed graphic setting to vulkan and now it works.

**Comment by Kayael76** [comment]
Ok, perfect, thanks for letting us know !
