### ISSUE TITLE
Resident Evil 3 Seamlesshdproject - File's image displayed on top of the text

### ISSUE THREAD

**Issue by Snakepayne** [MoArtis/ResidentEvilSeamlessHdProject#193]
Hey, can somebody please help me, I started playing res shdp and every time I read a file this happens ,I am using the us version iso, Thanks
This makes it impossible to read the letters and journals I pick up
![GLEE08-1](https://user-images.githubusercontent.com/75330321/100783785-13dfb780-33c3-11eb-8f53-70ad609a08e6.jpg)

**Comment by MoArtis** [comment]
What is your GPU model? AMD, right?

**Comment by MoArtis** [comment]
Try to change the backend to OpenGL in Graphics => General. But it's likely to not fix the issue. 🤔 Revert that option to what it was if it doesn't work.

**Comment by Snakepayne** [comment]
I am using an hd6870, could the card be causing the problem?

**Comment by MoArtis** [comment]
Sorry for the very late reply. But yeah people owning such Radeon card reported that same issue.

Maybe try our latest build of Dolphin: 
https://drive.google.com/u/3/uc?id=1AP99MgyMQqPmEfL3P1MZxXY5pI6lDFry&export=download
