### ISSUE TITLE
Request for missing .dds file (Jill's side pack model)

### ISSUE THREAD

**Issue by RE3NHANCED** [MoArtis/ResidentEvilSeamlessHdProject#195]
Hi there is a missing .dds file for the side pack model of Jill and there is a file with a side pack but it's incomplete i think (see attached image)...actually i do a character mod for your project https://www.moddb.com/mods/resident-evil-3-nemesis-re3nhanced hopefully you may grant my request so that someday I will finish the character texture mod. I really appreciate your project and I'm a big fan :)
![tex1_256x256_$_c5ecbc7e530fa9d7_9](https://user-images.githubusercontent.com/80968574/111797885-8211a100-8904-11eb-8ab2-ed06819093f4.png)

**Comment by MoArtis** [comment]
Just noticed your message. Thank you! Do you still need our support somehow?

**Comment by RE3NHANCED** [comment]
Hi my bad i already fix it, your files aren’t incomplete, it’s just my graphic software’s corrupted ad-on’s, now i already fix it thank you.

**Comment by RE3NHANCED** [comment]
> Just noticed your message. Thank you! Do you still need our support somehow?

As of now none...you guys are awesome thanks a lot! :)

![Uploading E1DCE2C6-3182-4198-A21C-2D5A64AEBEBB.png…]()

**Comment by MoArtis** [comment]
Alright perfect! And great job on your mod! 👍 Keep it up!
