### ISSUE TITLE
RESIDENT EVIL: TRUE DIRECTOR’S CUT

### ISSUE THREAD

**Issue by hondasbathroom** [MoArtis/ResidentEvilSeamlessHdProject#197]
It's been known that you are making a original RE Seamless Project, so it could be in hand to use this very complete version of the game that was arranged by Dely295 from Romhacking.net. Check in the link below:

http://www.romhacking.net/hacks/5837/

**Comment by xuru-thor** [comment]
That is a ROM for the Playstation version. Right now, it is impossible to replace textures with PSX emulation, so the Mediakite PC version of the game will be used. Right now, we're waiting for modders to be able to implement HD texture support into the game so we can do our work. 
It would also be appreciated if you didn't share any links or info about ROMs, as it is considered piracy and could damage the actual project.

**Comment by vantablack333** [comment]
> That is a ROM for the Playstation version. Right now, it is impossible to replace textures with PSX emulation

Now it is. Check out DuckStation.
