### ISSUE TITLE
No Linux?!

### ISSUE THREAD

**Issue by MohamedBehery** [MoArtis/ResidentEvilSeamlessHdProject#200]
Hey, is it possible to make that modification on Linux's Dolphin emulator as well?

**Comment by MoArtis** [comment]
Yes, someone did it before. It should be possible to build the source for Linux. Exactly like the original Dolphin version.

**Comment by otaconworks** [comment]
> Hey, is it possible to make that modification on Linux's Dolphin emulator as well?

Here is a link to the Linux download from the Resident Evil Seamless HD Discord. Hope this helps

https://mega.nz/file/uB503KZK#t6tTMyAhY9kKBiBUDk6CgAULQqw3lO3jF0YOJ8g7ywo
