### ISSUE TITLE
Ver1.2 font is missing. 

### ISSUE THREAD

**Issue by wmh6081** [MoArtis/ResidentEvilSeamlessHdProject#201]
The experience is great! Although the plot is already very familiar. But the lack of subtitles still makes me feel imperfect. Is there a lack of Japanese fonts in my computer? Hope someone can tell me why？
![QQ20211218231109 (2)](https://user-images.githubusercontent.com/96344997/146646165-36e90507-bdc0-449a-ba19-f9259735c2ca.jpg)
![QQ20211218230946](https://user-images.githubusercontent.com/96344997/146646168-dfbbbf27-8b28-4b94-b8fe-c9e75b48886d.jpg)
![QQ20211218231054](https://user-images.githubusercontent.com/96344997/146646170-7bc6425f-3f8a-4aef-b117-d0a8e4726255.jpg)
![QQ20211218231109 (1)](https://user-images.githubusercontent.com/96344997/146646172-3f0a2f3a-5bf0-4d29-aaf2-a7ae89540c5d.jpg)

**Comment by Kayael76** [comment]
Hello, we didn't do the font textures for all languages so the best you can do if you intend to play in japanese is to : 
 - Go wherever you installed the RESHDP Dolphin emulator 
 - Open the folder User\Load\Textures\User Interface\Texts 
 - Remove the 5 font textures beginning by tex1_256x256_e41ff8810ab3499b

The font will now display correctly in their original resolution. Let us know if it worked for you.

**Comment by wmh6081** [comment]
Hello, I did what you said.
 Deleting only five fonts has no effect. I tried to delete all the files in Texts. It did successfully display Japanese, but the effect looked a little bad. What seems to be missing is a clear Japanese font to support the Japanese version. 
![QQ20211219085549](https://user-images.githubusercontent.com/96344997/146659792-9eb011a2-9ee0-45ab-b5fc-cb32369ea3b9.jpg)

**Comment by Kayael76** [comment]
You should'nt have deleted all the present files, but it's ok. All kind of texts will now be displayed in their original resolution.

Like I mentioned, we didn't do the textures for all languages because this is too much work. Most important is, you got it working with subtitles visible. Have fun with this mod :)
