### ISSUE TITLE
Stuttering ONLY RE2 Opening Cutscene and Menu’s

### ISSUE THREAD

**Issue by snoesevan** [MoArtis/ResidentEvilSeamlessHdProject#203]
Hello, I’ve been having an issue where the opening cutscene (and menu’s) of RE2 run extremely slow, and stutter constantly. I do not have this issue with any other cutscene, or the game itself. Prefetching textured did not help, any help would be greatly appreciated

**Comment by LanderMalta** [comment]
Hello, iam having same issue

**Comment by MoArtis** [comment]
Are you using the FMV pack? If so I would recommend to delete it.
In any case, try to disable vsync. It's unlikely to help but It can have some bad interactions with the driver settings.
