### ISSUE TITLE
I ask for help for Chaos Legion PC version

### ISSUE THREAD

**Issue by SakunoishVsEiueas** [MoArtis/ResidentEvilSeamlessHdProject#213]
Hello, I am looking for help for high resolution texture mapping for the Chaos Legion video game, also if it is possible to scale the resolution to 1080p, through a DLL.
![Sin título](https://user-images.githubusercontent.com/117762857/200979844-604e2077-29a1-4cb5-aff2-99e7d456f7dc.png)

**Comment by MoArtis** [comment]
I don't think we can help you. You probably just need to google it and hope for the best at this point.
