### ISSUE TITLE
Dolphin build can't support Switch Pro Controller

### ISSUE THREAD

**Issue by Lyzder** [MoArtis/ResidentEvilSeamlessHdProject#218]
The Dolphin build used for the HD projects doesn't support the controller while newer official builds do.

I'm not sure if it's a problem with just Switch Pro Controllers or SDL controllers in general. The emulator detects the controller as Direct Input gamepad but it doesn't register any inputs done by it.

**Comment by Lyzder** [comment]
I apologize, the support was already added by the latest build.

**Comment by Kayael76** [comment]
You can eventually use BetterJoy for Cemu (or ReWASD, but it's not free) to emulate an Xbox One controller.
