### ISSUE TITLE
Fresh Dolphin install

### ISSUE THREAD

**Issue by Thgilneerg** [MoArtis/ResidentEvilSeamlessHdProject#219]
Extracted Dolphin build and loaded rom. Pressed delete but nothing seems to happen, am i missing a step? Do i need to put the texture pack into the emulator folder or something? Any help would be greatly appreciated. (Tried getting into Discord server but wasnt working)

**Comment by Thgilneerg** [comment]
Can confirm after going into Dolphin folders user/load/textures, there are no custom textures in this "custom dolphin build" going to download the DDS and stick them in there

**Comment by Kayael76** [comment]
Sorry we missed that post, indeed this time the emulator and textures are separate to facilitate potential updates in the future. Custom refers to the fact that it has a few hacks og Dolphin doesn't have to correctly diplay all HD textures. Instructions are provided on the moddb page but you might have missed them.

**Comment by Thgilneerg** [comment]
Thank you i did follow the Moddb guide but got hung up on which folder needed to be in which directory. May i suggest showing the file path as: /textures/GHA or just instruct to copy and paste the extracted GHA folder into textures. All in all it works great and im pretty excited and thankful to be able to play this version of the game. <3
