### ISSUE TITLE
text under graphic

### ISSUE THREAD

**Issue by tomthumb117** [MoArtis/ResidentEvilSeamlessHdProject#220]
Hi,

I'm not sure if this is an issue with ResidentEvilSeamlessHdProject or the Resident Evil HD mod by TeamX.

I'm using Windows 10. Biohazard (mediakite) and adding, 1st, the Resident Evil HD mod by TeamX and then, 2nd, the Resident Evil Seamless Hd Project.

This happens on both Chris and Jill campaigns. I've played through both recently and it's only happening at this one location / camera angle. There is on screen text appearing underneath a graphic.

Thanks for your work. I haven't played original 1996 Resident Evil since the late 1990s. PSX version.

![re-error](https://github.com/MoArtis/ResidentEvilSeamlessHdProject/assets/101583741/f274a41d-f435-440c-b3bf-ffcb91697cbb)

**Comment by Kayael76** [comment]
It happens because you have the Arrange mode from the Director's Cut version enbaled (it's a native bug), you should rename or remove the bio1dc folder to enable normal mode bg (it's in the readme).

**Comment by tomthumb117** [comment]
Thanks for replying.
