### ISSUE TITLE
Wonky FMVs for RE3 on Dolphin

### ISSUE THREAD

**Issue by alphachadREgamer** [MoArtis/ResidentEvilSeamlessHdProject#240]
Just added the Seamless HD for the Dolphin emulator, and the opening FMVs appear wobbly and unfocused, warped even. I followed the instructions on tutorials, but something is still wrong. I’m guessing it’s the GLE file I downloaded from the FMV pack on the RESHDP page.

**Comment by MoArtis** [comment]
I don't recommend using the FMV pack. 
As we cannot replace the on-disc video files we had to do the next best thing and replace the videos frame by frame at runtimes. It's such a memory-intensive process that issues are to be expected on some machines.
