### ISSUE TITLE
Remove the annoying jap subtitles from RE2 and RE3 FMVs!

### ISSUE THREAD

**Issue by alphachadREgamer** [MoArtis/ResidentEvilSeamlessHdProject#241]
But try to keep or make the FMVs 1080p and/or 60fps without jap subtitles for the PC. I know they’re “baked in”, but surely there’s a way to remove them, or swap them with GC’s FMVs that don’t have them, right? RIGHT???

**Comment by Berzerk2k2** [comment]
For Resident Evil 2 try these:

https://www.moddb.com/games/resident-evil-2/downloads/resident-evil-2-cutscenes-1080p60-no-subtitles-default-part-1
https://www.moddb.com/games/resident-evil-2/downloads/resident-evil-2-cutscenes-1080p60-no-subtitles-default-part-2
https://www.moddb.com/games/resident-evil-2/downloads/resident-evil-2-cutscenes-1080p60-no-subtitles-default-part-3

https://www.moddb.com/games/resident-evil-2/downloads/resident-evil-2-cutscenes-1080p60-no-subtitles-resized-part-1
https://www.moddb.com/games/resident-evil-2/downloads/resident-evil-2-cutscenes-1080p60-no-subtitles-resized-part-2
https://www.moddb.com/games/resident-evil-2/downloads/resident-evil-2-cutscenes-1080p60-no-subtitles-resized-part-3

For Resident Evil 3 try one of these:

https://www.moddb.com/games/resident-evil-3/downloads/re3-sourcenext-fmv-without-subtitles
https://www.moddb.com/mods/resident-evil-3-restoration-project/downloads/pc-re3-restoration-patch-v-0-9 (extract only the cutscenes from this pack)

The cutscenes in both of these RE3 packs don't include burnt in Japanese subtitles but they are only in 720x480p (they look still good even on a 1440p Monitor though).

**Comment by alphachadREgamer** [comment]
> For Resident Evil 2 try these:
> 
> https://www.moddb.com/games/resident-evil-2/downloads/resident-evil-2-cutscenes-1080p60-no-subtitles-default-part-1 https://www.moddb.com/games/resident-evil-2/downloads/resident-evil-2-cutscenes-1080p60-no-subtitles-default-part-2 https://www.moddb.com/games/resident-evil-2/downloads/resident-evil-2-cutscenes-1080p60-no-subtitles-default-part-3
> 
> https://www.moddb.com/games/resident-evil-2/downloads/resident-evil-2-cutscenes-1080p60-no-subtitles-resized-part-1 https://www.moddb.com/games/resident-evil-2/downloads/resident-evil-2-cutscenes-1080p60-no-subtitles-resized-part-2 https://www.moddb.com/games/resident-evil-2/downloads/resident-evil-2-cutscenes-1080p60-no-subtitles-resized-part-3
> 
> For Resident Evil 3 try one of these:
> 
> https://www.moddb.com/games/resident-evil-3/downloads/re3-sourcenext-fmv-without-subtitles https://www.moddb.com/mods/resident-evil-3-restoration-project/downloads/pc-re3-restoration-patch-v-0-9 (extract only the cutscenes from this pack)
> 
> The cutscenes in both of these RE3 packs don't include burnt in Japanese subtitles but they are only in 720x480p (they look still good even on a 1440p Monitor though).

Thanks, but I’ve already tried these, and visually, they're subpar and substandard to the Sourcenext FMVs. If you can figure out a way to maintain the beautiful, crisp, 1440p FMVs without the jap subtitles “baked in” for RE2 and RE3, then I’ll be very happy! Until then, thanks… but no thanks.

By the way, can you edit the typo of “electornically” at the sewer door after defeating the alligator to properly read “electronically”? Thanks!

**Comment by Berzerk2k2** [comment]
> Thanks, but I’ve already tried these, and visually, they're subpar and substandard to the Sourcenext FMVs. If you can figure out a way to maintain the beautiful, crisp, 1440p FMVs without the jap subtitles “baked in” for RE2 and RE3, then I’ll be very happy! Until then, thanks… but no thanks.

The linked cutscenes are the best option you can get at the moment. Getting the original RE2 SourceNext version cutscenes to have no subtitles would require to edit them frame by frame and there just isn't another RE2 cutscene source without subs available that has the same quality so you could use it to paint over the Japanese subs. The RE2 cutscenes linked above are based on the Dreamcast console version, which is the best looking version without subtitles available.
Maybe for RE3 someone can upscale one of these two cutscene packs to 1080p at some point. I've never messed around with upscaling before so I don't know which tool would provide the best quality in the end.
 
> By the way, can you edit the typo of “electornically” at the sewer door after defeating the alligator to properly read “electronically”? Thanks!

I've no experience when it comes to something like this so that's something someone else has to fix.

**Comment by MoArtis** [comment]
Good explanation from @Berzerk2k2. Thanks for that. It's too labor-intensive to fix this. And we tried many approaches and tools to automatize the process but the results were always disappointing. 
I guess that you should complain to Capcom or SourceNext to have hard-burned the JP subtitles on these videos. 😔
