### ISSUE TITLE
BEWARE — RE2 Crash with Brad and Magnum

### ISSUE THREAD

**Issue by alphachadREgamer** [MoArtis/ResidentEvilSeamlessHdProject#242]
No matter what happens, if you try to kill Brad with the Magnum, on Arrange Mode Hard for PC, the game will crash. FIX THIS!!!!! 🤬😡

**Comment by MoArtis** [comment]
START TO UNDERSTAND THAT WE ARE NOT THE PEOPLE WHO MADE THESE GAMES AND THEIR PATCHES!!! 🤬😡
lmao
