### ISSUE TITLE
RE3: Sound cut-out during garage earthquake!

### ISSUE THREAD

**Issue by alphachadREgamer** [MoArtis/ResidentEvilSeamlessHdProject#243]
I noticed that the sound cuts out during the cutscene in the garage right before the ground gives out underneath Jill, and the prompts of “Climb up/Drop down” come up. In the PlayStation and GameCube versions, the sound doesn’t cut out, yet it does for PC Sourcenext and Dreamcast. 

Is there a way for someone to patch that?

**Comment by MoArtis** [comment]
Check with the great lad who worked on ClassicRebirth (the patch that allows us to run these PC ports on modern PCs).
But honestly, I wouldn't recommend you bother him with such minute details. The patch has mod support so maybe attempt a fix by yourself instead.
