### ISSUE TITLE
Reskin PC menu with Dreamcast menu?

### ISSUE THREAD

**Issue by alphachadREgamer** [MoArtis/ResidentEvilSeamlessHdProject#244]
Is it possible to re-skin the PC/Sourcenext option menu for Arrange mode to match the Dreamcast difficulty menu, so that the PC version also reads Rookie, Expert and Nightmare when selecting Arrange mode?

**Comment by Kayael76** [comment]
Yes, the bitmap containing the menu stuff can be edited with any photo editor to reflect those changes. They're somewhere in the hires folder, I don't remember where (not in bg and masks for sure).

**Comment by alphachadREgamer** [comment]
I don’t have photo editor, can’t somebody from the Seamless HD team do it and just upload it to the hires folder, so everyone can download it.

**Comment by Kayael76** [comment]
There are nicer ways to ask for things, so no, nobody will do it for you.

**Comment by alphachadREgamer** [comment]
You’re probably not bright enough, or creative enough to do it anyway. If it can be done, I’ll figure it out. You can piss off.

**Comment by Kayael76** [comment]
I just did all the upscales with their touch-ups and remade all the fonts and menus from scratch (including the one you want changed), but like Jon Snow, I know nothing. Sad day. Goodbye.
