### ISSUE TITLE
3D models missing upscaled textures

### ISSUE THREAD

**Issue by saeedalshaikhpygas** [MoArtis/ResidentEvilSeamlessHdProject#35]
his textures are already ripped and will be uploaded along other files 
![GHAE08-127](https://user-images.githubusercontent.com/48784335/54880423-772aef80-4e55-11e9-8407-13bbfad5cd7e.png)

**Comment by Kayael76** [comment]
Need to check and dump the special costumes (2 for Leon, 1 for Claire).

**Comment by MoArtis** [comment]
So we can consider this testable / done with the hacked wildcard feature? @Kayael76 😉

**Comment by Kayael76** [comment]
Definitely testable, I'm pretty sure some dumps would still be missing, the problem with doors seems almost corrected.

**Comment by MoArtis** [comment]
I actually added some doors and a spider texture to the Gdrive folder while dumping the map textures. (I copied your upscaled textures and added the new wildcarded name to it).

But I think we can close this task now.
