### ISSUE TITLE
ROOM_408_01 is broken

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#63]
It's a never ending surprise, but I never noticed the mask is broken at this place (not really noticeable until you stay behind it) : 

![GHAE08-24](https://user-images.githubusercontent.com/48800201/56476160-ff6fd500-6493-11e9-82df-6be2a04847bd.png)

The bridge up (room_408_05) is fine though : 

![GHAE08-23](https://user-images.githubusercontent.com/48800201/56476166-1ca4a380-6494-11e9-9566-4804cf450040.png)

Upon closer inspection, it looks like someone badly copy/paste a few pixels large square at the wrong place. Probably an oversight from the devs, but the GC version is displayed correctly, thus the mask bug. 

I'm correcting both the original and re-do an upscale which is available in my 042119 update. You'll need to generate a new mask from it and recut it.

**Comment by Kayael76** [comment]
Available in the 1.1 update folder.

**Comment by MoArtis** [comment]
The new files are stored in the 1.1 Pack folder.
To test a 1.1 Full pack, Copy the full pack folder and then copy the 1.1 pack one on top of it.

**Comment by Kayael76** [comment]
The fix is working as intended !
