### ISSUE TITLE
Blank spot in ROOM_10F_02

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#64]
I noticed a blank spot at the bottom of this BG, not sure why it's there but it was really noticeable so I corrected it. Available for processing in my 042119 update.

**Comment by Kayael76** [comment]
BG available for process in the 1.1 update folder

**Comment by MoArtis** [comment]
The new files are stored in the 1.1 Pack folder.
To test a 1.1 Full pack, Copy the full pack folder and then copy the 1.1 pack one on top of it.

**Comment by Kayael76** [comment]
Working as intended !
