### ISSUE TITLE
Adding a colored border on the font

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#66]
Just a proposition in order to be even closer to the original game.

![image](https://user-images.githubusercontent.com/3904610/56543912-7943b380-65a5-11e9-926f-270f93717d52.png)

![image](https://user-images.githubusercontent.com/3904610/56543932-86f93900-65a5-11e9-8cda-cf87faaad504.png)

**Comment by Kayael76** [comment]
I might end up redoing them entirely to avoid the jaggies, but it's pretty tricky since it has to match the exact size (or smaller) per character of the vanilla font sheet.

**Comment by MoArtis** [comment]
I see, so you need to redo them in a bit smaller size and add an outline that doesn't exceed the max size of the letter. 🤔 Let me know if I can help on anything.

**Comment by Kayael76** [comment]
I've been trying a new one : 
![GHAE08-50](https://user-images.githubusercontent.com/48800201/57185036-f97ee880-6ec4-11e9-9908-dcb9ce6eaf3d.png)

White and blue are smoothed, red & grey aren't. What do you think ?

**Comment by MoArtis** [comment]
I feel it is just a bit blurrier nothing that noticeable to be honest. But I understand your problem, if you want to add a proper outline you need to redo all the font, right? since all the space is already taken. 😰

![image](https://user-images.githubusercontent.com/3904610/57186951-56f15480-6f1a-11e9-9681-54b07797cc1e.png)

For now the added blur make the color bleed improperly. You used bi-linear filtering?

**Comment by Kayael76** [comment]
Available in the 1.1 update. I redid them better (hopefully).

**Comment by Kayael76** [comment]
I'm pretty satisified with it, not perfect but that's the best I can get without redoing it from scratch. If it's okay for you after trying it a bit, we can close this.

**Comment by MoArtis** [comment]
Much more readable and smoother than before. 👌 I could argue that the colored font should have an outline of a similar color but it's almost the case already thanks to the color blending. And there is point when we need to stop improving something. 😂 Let's close this!
