### ISSUE TITLE
Vectorize the alpha channel of special FX

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#67]
It should be possible to automatize the entire process.

![image](https://user-images.githubusercontent.com/3904610/56849593-0af64c80-6929-11e9-9278-880f2c36a7ee.png)

**Comment by MoArtis** [comment]
We do have a pretty big selection of styles available now. Let's make a choice and close this issue for good. ;) @Kayael76

**Comment by MoArtis** [comment]
I do recommend to stick to Waifu+xBRZ as it features less inconsistencies quality-wise.

**Comment by Kayael76** [comment]
Yes I was going to say that. Since I still don't know how RE3 can be fixed on that part anyway, the dumps here will remain with Waifu so the quality will be consistent between both games too.

**Comment by MoArtis** [comment]
Ok I will move the all the older FX packs somewhere to keep the full pack and the 1.1 pack clean.
