### ISSUE TITLE
Manually edit smaller, most jarring and unprocessable details on Doors

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#68]
Not a priority and I didn't notice many jarring examples. It's usually some big texts becoming pastel oil or a keyhole / screws ending up looking very weird like this one:

![image](https://user-images.githubusercontent.com/3904610/56858079-4a637e00-69a7-11e9-975c-eb6687e01a99.png)

![image](https://user-images.githubusercontent.com/3904610/56858072-3c156200-69a7-11e9-871b-93f2eb7a571e.png)

**Comment by Kayael76** [comment]
Knowing that a single door can be dumped several times, it's not going to be easy to find them all :-/

**Comment by MoArtis** [comment]
With the hacked wildcard feature that should be feasible now, rigth? 
If needed, I can do some of these details myself.

**Comment by Kayael76** [comment]
If you spot something nasty to you don't hesitate to report it, I'll take a closer look tomorrow and see what I can do 👍 There shouldn't be too much of this.

**Comment by MoArtis** [comment]
![tex1_256x256_$_99d76b1cfa6e96c9_9](https://user-images.githubusercontent.com/3904610/59549503-22e56680-8f91-11e9-8323-39d2b237691b.png)

It's baby tier editing but it might do the job. Here is a video of it in action:
https://streamable.com/euv9r

I saw nothing else shocking upon further inspection. So if you are fine with this new texture, we can close the whole issue.

**Comment by Kayael76** [comment]
I'm perfectly fine with this 👍 good job !
