### ISSUE TITLE
Adding complementary information about the pack on the website

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#70]
It's been suggested to me and since it's bound to happen in the future, we should add a section stating that the pack is optimized for the NTSC version of the game, that PAL version works if you rename the folder GHAP08 but all foreign language stuff as well as other textures won't be upscaled. That would avoid confusion and not being constantly asked about it.

**Comment by MoArtis** [comment]
Ok! I was also thinking about adding an FAQ somewhere. Do you have other ideas of important information we need to address on the website?

**Comment by Kayael76** [comment]
- That we will never provide an iso, seems obvious but if Capcom decides to poke its nose around, at least we advertise it clearly.

- The support of the PC version that will come if it's supported some day but for now nothing can't really be done.

- About the RE1 and RE3 coming soon : we're investigating but can't promise anything for now

- Maybe pointing to the Dolphin board for anything related to the emulator itself (configuration, how to use, etc... )

That sums up the questions I was asked over time

**Comment by Kayael76** [comment]
We need to be more precise about the two packs, I had a newcomer knowing nothing on Dolphin who downloaded both and was lost.

**Comment by MoArtis** [comment]
I read a Russian person confused about the texture folder location and renaming it when using a Non-NTSC version of the game.

**Comment by MoArtis** [comment]
![image](https://user-images.githubusercontent.com/3904610/57118884-b6bff200-6d98-11e9-8db0-6e1161c68404.png)

Maybe he thought the game would be included. 🤔 But a step by step "installation" guide might be needed even if we made sure to make it as simple as possible.

**Comment by Kayael76** [comment]
Yep that might help as well.

On another note, a spanish guy made a spanish translation pack for the PAL version, can we add a section for stuff like this ?

**Comment by MoArtis** [comment]
I don't think so but it would be nice to cover the pal version in the future. 

I can also add a game patch to Dolphin to force it to run at 60hz.

**Comment by MoArtis** [comment]
And here is the FAQ section. Adding more will make the site more clunky to navigate I feel. Give it a try and let me know.

![image](https://user-images.githubusercontent.com/3904610/57188186-0afbdb00-6f2d-11e9-93f6-7a4c20b0e82c.png)
