### ISSUE TITLE
DX12 Crash when a lot of zombies appear

### ISSUE THREAD

**Issue by retconn** [MoArtis/ResidentEvilSeamlessHdProject#85]
If there are a lot of enemies on screen or during a cutscene such as zombies breaking through the glass that kill Kendo, or break through the fence in the ally, the game completely freezes 
![image](https://user-images.githubusercontent.com/44321681/57490043-f5b4e280-7285-11e9-9d92-54a6ddebf8d6.png)

**Comment by MoArtis** [comment]
Hello @retconn! Thank you for reporting this issue.

I'm no expert with Dolphin but have you changed any graphics settings?
On possible solution is to try other Graphics backends (Dx11, Vulkan or OpenGL. In this order).
Also try to make sure your GPU driver is up to date.

Let me know how it goes!

**Comment by retconn** [comment]
My laptop is a bit older, I switched it to OpenGL per your advice and it solved the issue. Thanks!

**Comment by MoArtis** [comment]
Perfect!

And if you experience slowdowns (and have something like 8GB of RAM), you can activate "Prefetch Custom Textures" (in the “Graphics” menu and the “Advanced” tab).
