### ISSUE TITLE
Missing upscaled BG on the RPD roof after putting the fire down

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#87]
https://i.imgur.com/6Wk6Z7Y.png

From ythealien on Discord

**Comment by Kayael76** [comment]
ROOM_11C_03 or 108_12 (they're the same)

Need to dump that first.

**Comment by Kayael76** [comment]
The dumps are available for matching in my 1.1 update folder.

**Comment by MoArtis** [comment]
I also remember a shot from that helicopter missing, but a more far away shot. Is that already fixed?

**Comment by Kayael76** [comment]
If there was one, it's been fixed for the release, 11C_03 is currently the only missing BG.

**Comment by MoArtis** [comment]
You are absolutely right. I just checked Albert_Fn_Wesker's stream and it is that exact room cut that is missing. So now I'm sure that I have Alzheimer. . . 😃

**Comment by MoArtis** [comment]
The new files are stored in the 1.1 Pack folder.
To test a 1.1 Full pack, Copy the full pack folder and then copy the 1.1 pack one on top of it.

**Comment by Kayael76** [comment]
Working as intended !
