### ISSUE TITLE
Remove the render mistake shadow from 219_02

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#90]
219_02
![image](https://user-images.githubusercontent.com/3904610/57590368-dc4db800-755d-11e9-8248-2526328c4840.png)

![image](https://user-images.githubusercontent.com/3904610/57590385-fbe4e080-755d-11e9-84b9-c30e99c4aca8.png)

**Comment by Kayael76** [comment]
Ok that's done and available for process in my 1.1 update folder. 

I also created a sub folder in the AMS for the broken vanilla BG that needs that kind of fixing before upscaling.

**Comment by MoArtis** [comment]
The new files are stored in the 1.1 Pack folder.
To test a 1.1 Full pack, Copy the full pack folder and then copy the 1.1 pack one on top of it.

**Comment by Kayael76** [comment]
Working as intended !
