### ISSUE TITLE
Upscale or Vectorize map textures

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#94]
Low priority and only justified if we can find a way automatize the work.

RE2 - The benefits is almost null, it will only make a difference for diagonal walls.
![GHAE08-2](https://user-images.githubusercontent.com/3904610/58378092-d32e0380-7fbf-11e9-83b3-d073cd6eb7cc.png)

RE3 - The difference will be much more noticeable (if the player opens the map...) as the map is much more detailed. 
![GLEE08-3](https://user-images.githubusercontent.com/3904610/58378096-096b8300-7fc0-11e9-9916-6ba014c068d0.png)

**Comment by MoArtis** [comment]
The tool is done. The RE3's textures are dump, processed and available on the Gdrive.
We need to find a good way to dump the RE2 ones.

**Comment by MoArtis** [comment]
I added all the upscaled textures in "User Interface\Maps" (full pack and 1.1 pack). Please check it out.

I have to admit that I certainly missed some areas and special cases. But It's really a pain in the butt to dump these textures. I don't think it's a big deal for now though, we need to get done with the 1.1 pack asap.

**Comment by Kayael76** [comment]
Tested different areas and it seems good ! Yeah it's quite the pain, that's why I didn't bother with it in the first place.

**Comment by MoArtis** [comment]
Cool! Let's close this then.
