### ISSUE TITLE
Change the turn on / off texture pack hotkey to something easier to do

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#96]
It's currently set to ALT + F10 and F10 is already pause.

We can change it to TAB.

**Comment by Kayael76** [comment]
TAB is currently attributed to frame rate unlock. 
I went with F11 / F12 for dump / load in my personal configuration, I don't remember if they're attributed to something like save state or such.

**Comment by MoArtis** [comment]
Ah shit I wanted something easy to reach. Maybe we can get rid of that framerate unlock hotkey. I'm quite sure it's not a feature players need to activate / deactivate on the fly. 🤔

**Comment by Kayael76** [comment]
That depends, since you can't skip the ending FMVs for example, I usually speed up the emulation in these instances (and more generally for other titles / emulators too). I don't  know if many people do this though, but I'm kinda used to it lol. Though we can always make a small advertise if we set it to TAB.

**Comment by MoArtis** [comment]
welp that's true. For some reasons, I forgot that uncapping the framerate for emulators basically means speeding up the game. Too used to game development where everything is tied to a delta time. 😂
I'm really looking for a universal key (something present on every kb layout). F12 is used by default for cancelling the last loaded state. 
I thought about "~/`" but it can be very different from keyboard to keyboard. Like on an AZERTY kb, it's "²".
Maybe F11 is really not being assigned. Let's check that. (But it's kinda dangerous between that confusing pause function and the revert last loaded sate function...)

**Comment by Kayael76** [comment]
Yeah I learned that the tough way. But I think it's safe to remove the Other States Hotkeys and use their attributed kb touch.

**Comment by MoArtis** [comment]
I guess Delete is fine. It seems nothing is using it. Correct me if I'm wrong.

**Comment by Kayael76** [comment]
Seems good !

**Comment by MoArtis** [comment]
I'm testing it for quite some time and I guess it's not being used by any other function. :)
