### ISSUE TITLE
BG Mismatched in 88 - rail cannon room

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#97]
tex1_320x240_7ec81ed1730962ef_5 is associated to R50009 when it should be R50D16 (the PC upscale is mistakingly named, check it under 88 - Rail Cannon Room)

Good texture
![tex1_320x240_7ec81ed1730962ef_5 (good R50D16)](https://user-images.githubusercontent.com/48800201/59469822-3203d180-8e36-11e9-9a46-9f0e32d66482.png)

Bad texture
![tex1_320x240_7ec81ed1730962ef_5 (bad R50009)](https://user-images.githubusercontent.com/48800201/59469843-3e882a00-8e36-11e9-8644-3562c12b6294.png)

**Comment by MoArtis** [comment]
Wow. . . I wonder how this could have been mismatched. . . Maybe a texture is simply missing and since I lowered a lot the min match value, the closest one is still something very different. 🤔

**Comment by MoArtis** [comment]
tbt

**Comment by Kayael76** [comment]
Still not fixed

**Comment by MoArtis** [comment]
oh that's because I need to fix the stuff the other way around too: R50D04

**Comment by MoArtis** [comment]
![image](https://user-images.githubusercontent.com/3904610/60385814-5c08f500-9ac0-11e9-8662-a443a0d2052e.png)

**Comment by Kayael76** [comment]
Ah yes, I said in the OP that the good texture (showing the Tyrant) is in fact R50D16, that's why it doesn't work.

**Comment by MoArtis** [comment]
So it was not a mismatch issue. Just a naming issue. I actually misunderstood your op. ahah No problem though but why not just fixing the upscale folder at the time? (you were at work I guess) Cool anyway! the 3 same issues will be fixed in 5 minutes then. 😉

**Comment by Kayael76** [comment]
I can't really say why. But the same can be applied for the balcony so I'm gonna take a look at it and rename the BG correctly.

**Comment by MoArtis** [comment]
I actually already renamed these ones (like all the other opened issues) but I guess you already noticed that. anyway it's fixed now. Working fine now.
