### ISSUE TITLE
BG mismatched in 88 - rail cannon room

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#98]
tex1_640x480_13fd82539f22bed0_5 is correctly associated to PC upscale R50D04 but displays in-game R40D09

Good texture
![tex1_640x480_13fd82539f22bed0_5 (good)](https://user-images.githubusercontent.com/48800201/59469736-f5d07100-8e35-11e9-8041-51c08d021961.png)

Bad texture in game
![tex1_640x480_13fd82539f22bed0_5 (bad)](https://user-images.githubusercontent.com/48800201/59469754-041e8d00-8e36-11e9-8c3b-f882de3cdf3f.png)

**Comment by MoArtis** [comment]
tbt

**Comment by Kayael76** [comment]
Still not fixed

**Comment by MoArtis** [comment]
Apparently the problem doesn't come from R40D09... a duplicate maybe?

**Comment by MoArtis** [comment]
R40D09 doesn't have a upscaled bg... so you can be sure it's a duplicate fucking with us. (But it's also potentially bad for R40D09 as it GC name might never be generated with an upscale)

**Comment by MoArtis** [comment]
![image](https://user-images.githubusercontent.com/3904610/60385797-28c66600-9ac0-11e9-8693-64d8b7a7ac70.png)
LOL
All these theory for just a little mistake. Good for that Room at least.

**Comment by MoArtis** [comment]
Fixed and tested
